# Generated by Django 5.0 on 2023-12-18 09:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lancer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=100)),
                ('uid', models.UUIDField(default=uuid.uuid4)),
                ('otp', models.CharField(max_length=100)),
                ('pfp', models.ImageField(upload_to='lancer_pics')),
                ('is_superuser', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=100)),
                ('message', models.CharField(default='', max_length=300)),
                ('files', models.FileField(blank=True, null=True, upload_to='lancer_project_files/')),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('notpaid', 'Not Paid')], default='notpaid', max_length=20)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('link', models.SlugField(unique=True)),
                ('razor_pay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razor_pay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razor_pay_payment_signature', models.CharField(blank=True, max_length=100, null=True)),
                ('lancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='main.lancer')),
            ],
        ),
    ]
