# Generated by Django 5.0 on 2023-12-18 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_tempfile_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempfile',
            name='number',
            field=models.CharField(default=23, max_length=100),
            preserve_default=False,
        ),
    ]
